/**********************************************************************
--- Qt Architect generated file ---
File: IconSelectDlgData.cpp
Last generated: Tue Apr 18 15:52:48 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "IconSelectDlgData.h"

IconSelectDlgData::IconSelectDlgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	List = new QListBox(this, "ListBox_2");
	List->setGeometry(10, 20, 470, 250);
	List->setMinimumSize(0, 0);
	List->setMaximumSize(32767, 32767);
	List->setFocusPolicy(QWidget::TabFocus);
	List->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	List->setFontPropagation(QWidget::SameFont);
	List->setPalettePropagation(QWidget::SameFont);
	#endif
	List->setFrameStyle( 34 );
	List->setLineWidth( 2 );
	List->setMidLineWidth( 0 );
	List->QFrame::setMargin( 0 );
	List->setDragSelect( TRUE );
	List->setAutoScroll( TRUE );
	List->setScrollBar( TRUE );
	List->setAutoScrollBar( TRUE );
	List->setBottomScrollBar( TRUE );
	List->setAutoBottomScrollBar( TRUE );
	List->setSmoothScrolling( FALSE );
	List->setMultiSelection( FALSE );
	List->setAutoUpdate( TRUE );
	QPushButton *qtarch_PushButton_3 = new QPushButton(this, "PushButton_3");
	qtarch_PushButton_3->setGeometry(10, 290, 100, 30);
	qtarch_PushButton_3->setMinimumSize(0, 0);
	qtarch_PushButton_3->setMaximumSize(32767, 32767);
	qtarch_PushButton_3->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_3->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_3->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_3->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_3->setText( tr( "Ok" ) );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );
	qtarch_PushButton_3->setToggleButton( FALSE );
	qtarch_PushButton_3->setDefault( FALSE );
	qtarch_PushButton_3->setAutoDefault( TRUE );
	qtarch_PushButton_3->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_3, SIGNAL(clicked()), SLOT(accept()));
	QPushButton *qtarch_PushButton_4 = new QPushButton(this, "PushButton_4");
	qtarch_PushButton_4->setGeometry(380, 290, 100, 30);
	qtarch_PushButton_4->setMinimumSize(0, 0);
	qtarch_PushButton_4->setMaximumSize(32767, 32767);
	qtarch_PushButton_4->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_4->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_4->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_4->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_4->setText( tr( "Cancel" ) );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );
	qtarch_PushButton_4->setToggleButton( FALSE );
	qtarch_PushButton_4->setDefault( FALSE );
	qtarch_PushButton_4->setAutoDefault( TRUE );
	qtarch_PushButton_4->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_4, SIGNAL(clicked()), SLOT(reject()));
	resize(490,330);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
IconSelectDlgData::~IconSelectDlgData()
{
}

