/**********************************************************************
--- Qt Architect generated file ---
File: IconSelectDlgData.h
Last generated: Tue Apr 18 15:52:48 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef IconSelectDlgData_included
#define IconSelectDlgData_included
#include <qt.h>

class IconSelectDlgData : public QDialog
{
	Q_OBJECT
	public:
	IconSelectDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~IconSelectDlgData();
	protected:
	QListBox *List;
};
#endif // IconSelectDlgData_included

