/**********************************************************************
--- Qt Architect generated file ---
File: SelectActiveDlgData.h
Last generated: Thu Sep 7 14:21:20 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SelectActiveDlgData_included
#define SelectActiveDlgData_included
#include <qt.h>

class SelectActiveDlgData : public QDialog
{
	Q_OBJECT
	public:
	SelectActiveDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SelectActiveDlgData();
	protected slots:
	virtual void NameChanged(int) =0;
	protected:
    QComboBox* Name;
    QListBox* IconList;
    QComboBox* TagList;
    QComboBox* ValueList;
    QComboBox* BLList;
    QComboBox* SBList;
    QComboBox* NTList;
    QComboBox* IVList;
};
#endif // SelectActiveDlgData_included

