/**********************************************************************
--- Qt Architect generated file ---
File: SetPenStyleData.h
Last generated: Fri Jun 16 13:53:19 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SetPenStyleData_included
#define SetPenStyleData_included
#include <qt.h>
class SetPenStyleData : public QDialog
{
	Q_OBJECT
	public:
	SetPenStyleData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SetPenStyleData();
	protected:
	QComboBox *Thickness;
	QComboBox *Style;
};
#endif // SetPenStyleData_included

