/**********************************************************************
--- Qt Architect generated file ---
File: SetPenStyleData.cpp
Last generated: Fri Jun 16 13:53:19 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "SetPenStyleData.h"

SetPenStyleData::SetPenStyleData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	Thickness = new QComboBox(FALSE, this, "ComboBox_1");
	Thickness->setGeometry(20, 20, 100, 30);
	Thickness->setMinimumSize(0, 0);
	Thickness->setMaximumSize(32767, 32767);
	Thickness->setFocusPolicy(QWidget::StrongFocus);
	Thickness->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Thickness->setFontPropagation(QWidget::SameFont);
	Thickness->setPalettePropagation(QWidget::SameFont);
	#endif
	Thickness->setSizeLimit( 10 );
	Thickness->setAutoResize( FALSE );
	Thickness->insertItem( tr( "Fine" ) );
	Thickness->insertItem( tr( "Thin" ) );
	Thickness->insertItem( tr( "Medium" ) );
	Thickness->insertItem( tr( "Thick" ) );
	Thickness->setMaxCount( 10 );
	Thickness->setAutoCompletion( FALSE );
	Style = new QComboBox(FALSE, this, "ComboBox_2");
	Style->setGeometry(170, 20, 100, 30);
	Style->setMinimumSize(0, 0);
	Style->setMaximumSize(32767, 32767);
	Style->setFocusPolicy(QWidget::StrongFocus);
	Style->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Style->setFontPropagation(QWidget::SameFont);
	Style->setPalettePropagation(QWidget::SameFont);
	#endif
	Style->setSizeLimit( 4 );
	Style->setAutoResize( FALSE );
	Style->insertItem( tr( "Solid" ) );
	Style->insertItem( tr( "Dash" ) );
	Style->insertItem( tr( "Dot" ) );
	Style->setMaxCount( 4 );
	Style->setAutoCompletion( FALSE );
	QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
	qtarch_PushButton_1->setGeometry(100, 60, 90, 30);
	qtarch_PushButton_1->setMinimumSize(0, 0);
	qtarch_PushButton_1->setMaximumSize(32767, 32767);
	qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_1->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_1->setText( tr( "Ok" ) );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setToggleButton( FALSE );
	qtarch_PushButton_1->setDefault( FALSE );
	qtarch_PushButton_1->setAutoDefault( FALSE );
	qtarch_PushButton_1->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_1, SIGNAL(clicked()), SLOT(accept()));
	resize(290,100);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
SetPenStyleData::~SetPenStyleData()
{
}

