/**********************************************************************
--- Qt Architect generated file ---
File: Modbus_driverConfigurationData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Modbus_driverConfigurationData_included
#define Modbus_driverConfigurationData_included

#include <qt.h>

class Modbus_driverConfigurationData : public QDialog
{
	Q_OBJECT
	public:
	Modbus_driverConfigurationData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Modbus_driverConfigurationData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QSpinBox *NItems;
	QSpinBox *PollInterval;
	//QLineEdit *OpcServerProgIDText;
	QLineEdit *IEC104ServerIPAddressText;
};
#endif // Modbus_driverConfigurationData_included

