/**********************************************************************
--- Qt Architect generated file ---
File: modbus_masterCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef modbus_masterCommandData_included
#define modbus_masterCommandData_included

#include <qt.h>
#include "valedit.h"

class modbus_masterCommandData : public QDialog
{
	Q_OBJECT
	public:
	modbus_masterCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~modbus_masterCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // modbus_masterCommandData_included

