/**********************************************************************
--- Qt Architect generated file ---
File: modbus_masterInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef modbus_masterInputData_included
#define modbus_masterInputData_included
#include <qt.h>
#include "valedit.h"
class modbus_masterInputData : public QWidget
{
	Q_OBJECT
	public:
	modbus_masterInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~modbus_masterInputData();
	protected:
	//TIMEEDIT *Time;
	//INTEDIT *Mean;
	//INTEDIT *Variation;
	INTEDIT *IOA;
};
#endif // modbus_masterInputData_included

