/**********************************************************************
--- Qt Architect generated file ---
File: Mpi_driverConfigurationData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Mpi_driverConfigurationData_included
#define Mpi_driverConfigurationData_included

#include <qt.h>

class Mpi_driverConfigurationData : public QDialog
{
	Q_OBJECT
	public:
	Mpi_driverConfigurationData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Mpi_driverConfigurationData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QSpinBox *NItems;
	QLineEdit *MPIServerIPAddressText;
	QLineEdit *MPIServerIPPortText;
	QLineEdit *MPIServerSlotText;
	QLineEdit *PLCAddressText;
};
#endif // Mpi_driverConfigurationData_included

