/**********************************************************************
--- Qt Architect generated file ---
File: Mpi_driverInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Mpi_driverInputData_included
#define Mpi_driverInputData_included
#include <qt.h>
#include "valedit.h"
class Mpi_driverInputData : public QWidget
{
	Q_OBJECT
	public:
	Mpi_driverInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Mpi_driverInputData();
	protected:
	//TIMEEDIT *Time;
	//INTEDIT *Mean;
	//INTEDIT *Variation;
	INTEDIT *IOA;
};
#endif // Mpi_driverInputData_included

