/**********************************************************************
--- Qt Architect generated file ---
File: InputDlgData.h
Last generated: Tue Apr 18 15:50:33 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef InputDlgData_included
#define InputDlgData_included
#include <qt.h>

class InputDlgData : public QDialog
{
	Q_OBJECT
	public:
	InputDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~InputDlgData();
	protected:
	QLineEdit *Name;
};
#endif // InputDlgData_included

