/**********************************************************************
--- Qt Architect generated file ---
File: Opcua_driverInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Opcua_driverInputData_included
#define Opcua_driverInputData_included
#include <qt.h>
#include "valedit.h"
class Opcua_driverInputData : public QWidget
{
	Q_OBJECT
	public:
	Opcua_driverInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Opcua_driverInputData();
	protected:
	//TIMEEDIT *Time;
	//INTEDIT *Mean;
	//INTEDIT *Variation;
	INTEDIT *IOA;
};
#endif // Opcua_driverInputData_included

