/**********************************************************************
--- Qt Architect generated file ---
File: Iec104driverInputData.cpp
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "iec104driverInputData.h"


Iec104driverInputData::Iec104driverInputData(QWidget *parent, const char *name)
: QWidget(parent, name, 0)
{
	/*
	QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
	qtarch_Label_2->setGeometry(10, 10, 120, 30);
	qtarch_Label_2->setMinimumSize(0, 0);
	qtarch_Label_2->setMaximumSize(32767, 32767);
	qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_2->setFontPropagation(QWidget::SameFont);
	qtarch_Label_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setLineWidth( 1 );
	qtarch_Label_2->setMidLineWidth( 0 );
	qtarch_Label_2->QFrame::setMargin( 0 );
	qtarch_Label_2->setText( tr( "Sampling Period" ) );
	qtarch_Label_2->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_2->setMargin( 0 );
	Time = new TIMEEDIT(this, "User_1");
	Time->setGeometry(40, 50, 70, 30);
	Time->setMinimumSize(0, 0);
	Time->setMaximumSize(32767, 32767);
	Time->setFocusPolicy(QWidget::StrongFocus);
	Time->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	Time->setFontPropagation(QWidget::SameFont);
	Time->setPalettePropagation(QWidget::SameFont);
	#endif
	QLabel *qtarch_Label_3 = new QLabel(this, "Label_3");
	qtarch_Label_3->setGeometry(150, 10, 90, 30);
	qtarch_Label_3->setMinimumSize(0, 0);
	qtarch_Label_3->setMaximumSize(32767, 32767);
	qtarch_Label_3->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_3->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_3->setFontPropagation(QWidget::SameFont);
	qtarch_Label_3->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_3->setFrameStyle( 0 );
	qtarch_Label_3->setLineWidth( 1 );
	qtarch_Label_3->setMidLineWidth( 0 );
	qtarch_Label_3->QFrame::setMargin( 0 );
	qtarch_Label_3->setText( tr( "Mean Value" ) );
	qtarch_Label_3->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_3->setMargin( 0 );
	QLabel *qtarch_Label_4 = new QLabel(this, "Label_4");
	qtarch_Label_4->setGeometry(260, 10, 100, 30);
	qtarch_Label_4->setMinimumSize(0, 0);
	qtarch_Label_4->setMaximumSize(32767, 32767);
	qtarch_Label_4->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_4->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_4->setFontPropagation(QWidget::SameFont);
	qtarch_Label_4->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setLineWidth( 1 );
	qtarch_Label_4->setMidLineWidth( 0 );
	qtarch_Label_4->QFrame::setMargin( 0 );
	qtarch_Label_4->setText( tr( "Variation +/-" ) );
	qtarch_Label_4->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_4->setMargin( 0 );
	Mean = new INTEDIT(this, "User_2");
	Mean->setGeometry(160, 50, 70, 30);
	Mean->setMinimumSize(0, 0);
	Mean->setMaximumSize(32767, 32767);
	Mean->setFocusPolicy(QWidget::StrongFocus);
	Mean->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	Mean->setFontPropagation(QWidget::SameFont);
	Mean->setPalettePropagation(QWidget::SameFont);
	#endif
	Variation = new INTEDIT(this, "User_3");
	Variation->setGeometry(270, 50, 70, 30);
	Variation->setMinimumSize(0, 0);
	Variation->setMaximumSize(32767, 32767);
	Variation->setFocusPolicy(QWidget::StrongFocus);
	Variation->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	Variation->setFontPropagation(QWidget::SameFont);
	Variation->setPalettePropagation(QWidget::SameFont);
	#endif
	resize(400,100);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
	*/

	QLabel *qtarch_Label_4 = new QLabel(this, "Label_4");
	qtarch_Label_4->setGeometry(260, 10, 100, 30);
	qtarch_Label_4->setMinimumSize(0, 0);
	qtarch_Label_4->setMaximumSize(32767, 32767);
	qtarch_Label_4->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_4->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_4->setFontPropagation(QWidget::SameFont);
	qtarch_Label_4->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setLineWidth( 1 );
	qtarch_Label_4->setMidLineWidth( 0 );
	qtarch_Label_4->QFrame::setMargin( 0 );
	qtarch_Label_4->setText( tr( "IOA" ) );
	qtarch_Label_4->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_4->setMargin( 0 );

	IOA = new INTEDIT(this, "User_3");
	IOA->setGeometry(270, 50, 70, 30);
	IOA->setMinimumSize(0, 0);
	IOA->setMaximumSize(32767, 32767);
	IOA->setFocusPolicy(QWidget::StrongFocus);
	IOA->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	IOA->setFontPropagation(QWidget::SameFont);
	IOA->setPalettePropagation(QWidget::SameFont);
	#endif
	resize(400,100);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);

}

Iec104driverInputData::~Iec104driverInputData()
{
}


/*
Iec104driverInputData::Iec104driverInputData(QWidget *parent, const char *name)
: QWidget(parent, name, 16)
{
	QLabel *qtarch_Label_13 = new QLabel(this, "Label_13");
	qtarch_Label_13->setGeometry(0, 0, 50 , 30);
	qtarch_Label_13->setMinimumSize(0, 0);
	qtarch_Label_13->setMaximumSize(32767, 32767);
	qtarch_Label_13->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_13->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_13->setFontPropagation(QWidget::SameFont);
	qtarch_Label_13->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_13->setFrameStyle( 0 );
	qtarch_Label_13->setLineWidth( 1 );
	qtarch_Label_13->setMidLineWidth( 0 );
	qtarch_Label_13->QFrame::setMargin( 0 );
	qtarch_Label_13->setText( tr( "IOA" ) );
	qtarch_Label_13->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_13->setMargin( 0 );

	ItemID = new QLineEdit(this, "LineEdit_3");
	ItemID->setGeometry(50, 0, 500, 30);
	ItemID->setMinimumSize(0, 0);
	ItemID->setMaximumSize(32767, 32767);
	ItemID->setFocusPolicy(QWidget::StrongFocus);
	ItemID->setBackgroundMode(QWidget::PaletteBase);
	#if QT_VERSION < 300
	ItemID->setFontPropagation(QWidget::SameFont);
	ItemID->setPalettePropagation(QWidget::SameFont);
	#endif
	ItemID->setText( "" );
	ItemID->setMaxLength( 32767 );
	ItemID->setFrame( QLineEdit::Normal );
	ItemID->setFrame( TRUE );
	ItemID->setAlignment( AlignLeft );
	ItemID->setReadOnly( TRUE );

	QLabel *qtarch_Label_14 = new QLabel(this, "Label_13");
	qtarch_Label_14->setGeometry(0, 50, 80 , 30);
	qtarch_Label_14->setMinimumSize(0, 0);
	qtarch_Label_14->setMaximumSize(32767, 32767);
	qtarch_Label_14->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_14->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_14->setFontPropagation(QWidget::SameFont);
	qtarch_Label_14->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_14->setFrameStyle( 0 );
	qtarch_Label_14->setLineWidth( 1 );
	qtarch_Label_14->setMidLineWidth( 0 );
	qtarch_Label_14->QFrame::setMargin( 0 );
	qtarch_Label_14->setText( tr( "IEC Type" ) );
	qtarch_Label_14->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_14->setMargin( 0 );

	OPCType = new QLineEdit(this, "LineEdit_3");
	OPCType->setGeometry(80, 50, 200, 30);
	OPCType->setMinimumSize(0, 0);
	OPCType->setMaximumSize(32767, 32767);
	OPCType->setFocusPolicy(QWidget::StrongFocus);
	OPCType->setBackgroundMode(QWidget::PaletteBase);
	#if QT_VERSION < 300
	OPCType->setFontPropagation(QWidget::SameFont);
	OPCType->setPalettePropagation(QWidget::SameFont);
	#endif
	OPCType->setText( "" );
	OPCType->setMaxLength( 32767 );
	OPCType->setFrame( QLineEdit::Normal );
	OPCType->setFrame( TRUE );
	OPCType->setAlignment( AlignLeft );
	OPCType->setReadOnly( TRUE );

	QLabel *qtarch_Label_15 = new QLabel(this, "Label_13");
	qtarch_Label_15->setGeometry(300, 50, 80 , 30);
	qtarch_Label_15->setMinimumSize(0, 0);
	qtarch_Label_15->setMaximumSize(32767, 32767);
	qtarch_Label_15->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_15->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_15->setFontPropagation(QWidget::SameFont);
	qtarch_Label_15->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_15->setFrameStyle( 0 );
	qtarch_Label_15->setLineWidth( 1 );
	qtarch_Label_15->setMidLineWidth( 0 );
	qtarch_Label_15->QFrame::setMargin( 0 );
	qtarch_Label_15->setText( tr( "Writeble" ) );
	qtarch_Label_15->setAlignment( AlignHCenter|AlignVCenter|ExpandTabs );
	qtarch_Label_15->setMargin( 0 );

	IsWriteble = new QCheckBox( this, "CheckBox_8" );
	IsWriteble->setGeometry( 370, 50, 20, 20 );
	IsWriteble->setMinimumSize( 0, 0 );
	IsWriteble->setMaximumSize( 32767, 32767 );
	IsWriteble->setFocusPolicy( QWidget::TabFocus );
	IsWriteble->setBackgroundMode( QWidget::PaletteBackground );
	#if QT_VERSION < 300
	IsWriteble->setFontPropagation( QWidget::SameFont );
	IsWriteble->setPalettePropagation( QWidget::SameFont );
	#endif
	IsWriteble->setText( tr("Is writeble") );
	IsWriteble->setAutoRepeat( FALSE );
	IsWriteble->setAutoResize( FALSE );
	IsWriteble->setChecked( FALSE );
	
	
	resize(400,100);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
Iec104driverInputData::~Iec104driverInputData()
{
}

*/